In [1]:
import requests 
from bs4 import BeautifulSoup
import html
import pandas as pd, numpy as np 
from io import StringIO
import math  
import sqlalchemy 
import re 

pd.set_option('display.max_columns', None) 
pd.set_option('display.max_rows', 50)

In [2]:
def clean_player(name): 
    i = name.find('*')   
    name = name[:i] if i > -1 else name 
    return name 

def load_soup(URL): 
    r = requests.get(URL) 
    soup = BeautifulSoup(r.content, 'html') 

    return soup 

def select_team(group):
    value = group.head(1) 
    if 'Team' in value.columns:
        if len(group) > 1: 
            value['Team'] = "" 
            for i in range(1, len(group)):
                value['Team'] += group.iloc[i]['Team'] 
                value['Team'] += '-' if i < len(group)-1 else ''  
    else: 
        if len(group) > 1: 
            value['Tm'] = "" 
            for i in range(1, len(group)):
                value['Tm'] += group.iloc[i]['Tm'] 
                value['Tm'] += '-' if i < len(group)-1 else ''  
    return value 

def html_df(soup, key, value, remove_cols=['Rk'], drop_cols=True, drop_lvl=False): 
    stat_df = soup.find('table', attrs={key:value}) 
    stat_df = pd.read_html(StringIO(str(stat_df))) 
    stat_df = pd.DataFrame(stat_df[0]) 
    if drop_lvl: 
        stat_df.columns = stat_df.columns.droplevel() 
    stat_df = stat_df.groupby('Player').apply(lambda x: select_team(x)).reset_index(drop=True) 
    stat_df['Player'] = stat_df['Player'].apply(lambda x: clean_player(x)) 
    if drop_cols==True:  
        stat_df = stat_df.drop(remove_cols, axis=1) 

    return stat_df 

def combine_dfs(dfs):
    curr = None
    for name in dfs.keys():
        if curr is None: 
            curr = dfs[name]
        else:
            diff = dfs[name].columns.difference(curr.columns).tolist()
            diff.append('Player') 
            curr = pd.merge(curr, dfs[name].loc[:,diff], on = 'Player') 
    return curr  

def clean_if_dirty(master):
    filtered = master[master['Player']=='Player']
    pos = filtered.index
    master = master.drop(pos, axis=0) 
    master['Player'] = master['Player'].apply(lambda x: clean_player(x)) 
    master = master.dropna(axis=1, how='all')   
    if ('Tm' in master.columns) & ('Team' in master.columns): 
        master = master.drop('Tm', axis=1) 
         
    return master 

def mod_types_pct(master): 
    for col_name in master.columns: 
        if col_name not in ['Player', 'Team', 'Tm', 'Pos', 'Awards']:  
            master[col_name] = master[col_name].astype("float64")
        if col_name in ['FG%', '3P%', 'FT%', 'eFG%', 'TS%', '2P%']:
            master[col_name] *= 100 
    return master

def process_totals(totals, names): 
    if '3P' in totals.columns:  
        totals = totals.loc[:,['PTS', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'MP', 'FG', 'FGA', '3P', '3PA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB']] 
    elif 'BLK' in totals.columns: 
        totals = totals.loc[:,['PTS', 'TRB', 'AST', 'STL', 'BLK', 'PF', 'MP', 'FG', 'FGA', '2P', '2PA', 'FT', 'FTA', 'ORB', 'DRB']] 
    elif 'TRB':
        totals = totals.loc[:,['PTS', 'TRB', 'AST', 'PF', 'FG', 'FGA', '2P', '2PA', 'FT', 'FTA']] 
    else: 
        totals = totals.loc[:,['PTS', 'AST', 'PF', 'FG', 'FGA', '2P', '2PA', 'FT', 'FTA']] 
    totals.columns = 'T' + totals.columns 
    totals['Player'] =  names 

    return totals 

def process_averages(master):
    if 'TOV' in master.columns: 
        new = master.rename(columns={'G':'GP', 'MP':'MPG', 'ORB':'ORPG', 'DRB':'DRPG', 'TRB':'RPG', 'AST':'APG', 'STL':'SPG', 'BLK':'BPG', 'TOV':'ToPG', 'PTS':'PPG'}, errors="raise")
    elif 'BLK' in master.columns: 
        new = master.rename(columns={'G':'GP', 'MP':'MPG', 'ORB':'ORPG', 'DRB':'DRPG', 'TRB':'RPG', 'AST':'APG', 'STL':'SPG', 'BLK':'BPG', 'PTS':'PPG'}, errors="raise") 
    elif 'TRB' in master.columns: 
        new = master.rename(columns={'G':'GP', 'TRB':'RPG', 'AST':'APG', 'PTS':'PPG'}, errors="raise") 
    else: 
        new = master.rename(columns={'G':'GP', 'AST':'APG','PTS':'PPG'}, errors="raise") 

    return new

In [3]:
engine1 = sqlalchemy.create_engine("sqlite:///../../DB/ballbase.db") 
engine2 = sqlalchemy.create_engine('postgresql+psycopg2://brandon:access@localhost:5432/ballbase' ) 
start_ssn = 2024     
stop_ssn = 2025                    

for season in range(start_ssn, stop_ssn): 
    
    URL_averages = 'https://www.basketball-reference.com/leagues/NBA_' + str(season+1) + '_per_game.html' 
    soup_averages = load_soup(URL_averages) 
    averages = html_df(soup_averages, 'id', 'per_game_stats', ['Rk'])  

    URL_totals = 'https://www.basketball-reference.com/leagues/NBA_' + str(season+1) + '_totals.html' 
    soup_totals = load_soup(URL_totals) 
    totals = html_df(soup_totals, 'id', 'totals_stats', ['Rk']) 
    totals = process_totals(totals, averages['Player'])   
    
    if season >= 1973: 
        URL_per100 = 'https://www.basketball-reference.com/leagues/NBA_' + str(season+1) + '_per_poss.html' 
        soup_per100 = load_soup(URL_per100) 
        try:
            per100 = html_df(soup_per100, 'id', 'per_poss', ['Rk', 'Unnamed: 29']) 
        except:
            per100 = html_df(soup_per100, 'id', 'per_poss', ['Rk']) 

    URL_advanced = 'https://www.basketball-reference.com/leagues/NBA_' + str(season+1) + '_advanced.html'  
    soup_advanced = load_soup(URL_advanced) 
    try: 
        advanced = html_df(soup_advanced, 'id', 'advanced', ['Rk', 'Unnamed: 19', 'Unnamed: 24'])  
    except:
        advanced = html_df(soup_advanced, 'id', 'advanced', ['Rk'])  

    if season >= 1973: 
        dfs = {"averages": averages, "totals": totals, "per100": per100, "advanced": advanced} 
    else: 
        dfs = {"averages": averages, "totals": totals, "advanced": advanced} 

    season_str = str(season) + '_' + str(season+1)[2:]
    master = combine_dfs(dfs) 
    master = clean_if_dirty(master) 
    master = mod_types_pct(master) 
    master = process_averages(master) 
    
    master.to_sql('master_'+season_str, con=engine1, if_exists='replace', index=False) 
    master.to_sql('master_'+season_str, con=engine2, if_exists='replace', index=False)

C:\Users\bchan\AppData\Local\Temp\ipykernel_19540\1912748627.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_df = stat_df.groupby('Player').apply(lambda x: select_team(x)).reset_index(drop=True)
C:\Users\bchan\AppData\Local\Temp\ipykernel_19540\1912748627.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_df = stat_df.groupby('Player').apply(lambda x: select_team(x)).reset_index(drop=True)
C:\Users\bchan\AppData\Local\Temp\ipykernel_19540\1912748627.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_df = stat_df.groupby('Player').apply(lambda x: select_team(x)).reset_index(drop=True)
C:\Users\bchan\AppData\Local\Temp\ipykernel_19540\1912748627.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_df = stat_df.groupby('Player').apply(lambda x: select_team(x)).reset_index(drop=True)
C:\Users\bchan\AppData\Local\Temp\ipykernel_19540\1912748627.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_df = stat_df.groupby('Player').apply(lambda x: select_team(x)).reset_index(drop=True)
C:\Users\bchan\AppData\Local\Temp\ipykernel_19540\1912748627.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stat_df = stat_df.groupby('Player').apply(lambda x: select_team(x)).reset_index(drop=True)

# Clean Tables

In [4]:
engine1 = sqlalchemy.create_engine("sqlite:///../../DB/ballbase.db") 
engine2 = sqlalchemy.create_engine('postgresql+psycopg2://brandon:access@localhost:5432/ballbase' ) 

start_ssn = 1973   
stop_ssn = 2025     

for season in range(start_ssn, stop_ssn):   
    season_str = str(season) + '_' + str(season+1)[2:] 
    master = pd.read_sql("master"+"_"+season_str, con=engine1)  

    # Cleaning code here ... 
    master.columns = master.columns.str.upper()    
    try:
        master = master.sort_values(by='ppg', ascending=False)
    except:
        master = master.sort_values(by='PPG', ascending=False)
    master.to_sql('master'+'_'+season_str, con = engine1, if_exists = 'replace', index = False)

In [5]:
engine = sqlalchemy.create_engine("sqlite:///../../DB/ballbase.db")
pd.read_sql('master_plt', con=engine)

,index,Player,Season,Pos,Age,Tm,GP,MPG,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORPG,DRPG,RPG,APG,SPG,BPG,ToPG,PF,PPG,T2P,T2PA,T3P,T3PA,TAST,TBLK,TDRB,TFG,TFGA,TFT,TFTA,TMP,TORB,TPF,TPTS,TSTL,TTOV,TTRB,DRtg,ORtg,3PAr,AST%,BLK%,BPM,DBPM,DRB%,DWS,FTr,OBPM,ORB%,OWS,PER,STL%,TOV%,TRB%,TS%,USG%,VORP,WS,WS/48,AS
0,0,Abdul Jeelani,1980,SF,25.0,POR,77.0,16.7,3.7,7.3,51.0,0.0,0.1,0.0,3.7,7.3,51.5,51.0,2.1,2.6,78.9,1.5,2.0,3.5,1.2,0.5,0.5,1.5,2.0,9.6,288.0,559.0,0.0,6.0,95.0,40.0,156.0,288.0,565.0,161.0,204.0,1286.0,114.0,155.0,737.0,40.0,117.0,270.0,104.0,109.0,0.011,11.6,1.8,1.5,-0.1,13.5,1.5,0.361,1.7,9.6,2.3,18.7,1.5,15.2,11.5,56.3,24.6,1.1,3.8,0.141,0.0
1,1,Adrian Dantley,1980,SF,24.0,UTA,68.0,39.3,10.7,18.6,57.6,0.0,0.0,NaN,10.7,18.6,57.7,57.6,6.5,7.7,84.2,2.7,4.9,7.6,2.8,1.4,0.2,3.4,3.1,28.0,730.0,1265.0,0.0,2.0,191.0,14.0,333.0,730.0,1267.0,443.0,526.0,2674.0,183.0,211.0,1903.0,96.0,233.0,516.0,110.0,119.0,0.002,12.3,0.3,3.7,-1.6,14.0,1.1,0.415,5.3,8.3,9.5,24.3,1.8,13.5,11.3,63.5,27.8,3.8,10.5,0.189,1.0
2,2,Al Skinner,1980,SG,27.0,PHI,2.0,5.0,0.5,1.0,50.0,0.0,0.0,NaN,0.5,1.0,50.0,50.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.5,1.0,1.0,2.0,0.0,0.0,2.0,0.0,0.0,1.0,2.0,0.0,0.0,10.0,0.0,1.0,2.0,0.0,2.0,0.0,111.0,65.0,0.000,25.4,0.0,-4.8,-0.2,0.0,0.0,0.000,-4.6,0.0,0.0,-0.6,0.0,50.0,0.0,50.0,16.0,0.0,0.0,-0.152,0.0
3,3,Alex English,1980,SF,26.0,IND-DEN,78.0,30.8,7.1,14.3,49.7,0.0,0.1,33.3,7.1,14.2,49.8,49.8,2.7,3.4,78.9,3.4,4.3,7.8,2.9,0.9,0.8,2.7,2.6,16.9,551.0,1107.0,2.0,6.0,224.0,62.0,336.0,553.0,1113.0,210.0,266.0,2401.0,269.0,206.0,1318.0,73.0,214.0,605.0,107.0,106.0,0.005,13.9,1.4,0.4,-1.2,14.9,2.0,0.239,1.6,11.3,3.3,18.0,1.4,14.8,13.1,53.6,23.4,1.5,5.3,0.105,0.0
4,4,Allan Bristow,1980,SF,28.0,UTA,82.0,28.1,4.6,9.6,48.0,0.0,0.1,28.6,4.6,9.5,48.2,48.2,2.4,3.0,81.1,2.1,4.2,6.2,4.2,1.1,0.1,2.2,2.6,11.6,375.0,778.0,2.0,7.0,341.0,6.0,342.0,377.0,785.0,197.0,243.0,2304.0,170.0,211.0,953.0,88.0,179.0,512.0,110.0,108.0,0.009,21.4,0.1,0.6,-0.8,16.7,1.2,0.310,1.4,9.0,3.2,16.6,1.9,16.7,13.0,53.4,20.0,1.5,4.4,0.091,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19370,19370,Zach LaVine,2024,SG,28.0,CHI,25.0,34.9,6.8,15.0,45.2,2.4,6.8,34.9,4.4,8.3,53.6,53.1,3.5,4.1,85.4,0.3,4.8,5.2,3.9,0.8,0.3,2.1,2.3,19.5,111.0,207.0,59.0,169.0,98.0,8.0,121.0,170.0,376.0,88.0,103.0,872.0,8.0,57.0,487.0,21.0,52.0,129.0,118.0,113.0,0.449,16.8,0.9,0.1,-0.7,15.8,0.6,0.274,0.8,1.0,0.8,15.1,1.2,11.0,8.3,57.8,23.8,0.5,1.5,0.080,0.0
19371,19371,Zavier Simpson,2024,PG,26.0,MEM,7.0,23.0,2.4,7.7,31.5,0.7,2.4,29.4,1.7,5.3,32.4,36.1,0.4,0.6,75.0,0.6,2.3,2.9,3.6,1.0,0.4,1.4,1.6,6.0,12.0,37.0,5.0,17.0,25.0,3.0,16.0,17.0,54.0,3.0,4.0,161.0,4.0,11.0,42.0,7.0,10.0,20.0,115.0,86.0,0.315,22.5,1.7,-5.9,0.3,11.3,0.2,0.074,-6.2,2.6,-0.3,6.3,2.1,15.2,6.8,37.7,17.5,-0.2,-0.2,-0.046,0.0
19372,19372,Zeke Nnaji,2024,PF,23.0,DEN,58.0,9.9,1.2,2.6,46.3,0.1,0.4,26.1,1.1,2.2,50.0,48.3,0.7,1.1,67.7,1.1,1.1,2.2,0.6,0.3,0.7,0.5,1.4,3.2,63.0,126.0,6.0,23.0,32.0,38.0,65.0,69.0,149.0,42.0,62.0,576.0,61.0,81.0,186.0,15.0,27.0,126.0,112.0,113.0,0.154,7.0,5.6,-3.7,0.1,12.2,0.8,0.416,-3.8,12.1,0.4,12.4,1.3,13.3,12.1,52.8,15.4,-0.2,1.2,0.099,0.0
19373,19373,Ziaire Williams,2024,SF,22.0,MEM,51.0,20.4,2.9,7.4,39.7,1.1,3.7,30.7,1.8,3.7,48.7,47.4,1.2,1.5,82.7,0.7,2.8,3.5,1.5,0.7,0.2,1.3,1.7,8.2,92.0,189.0,58.0,189.0,75.0,9.0,145.0,150.0,378.0,62.0,75.0,1038.0,35.0,85.0,420.0,36.0,66.0,180.0,115.0,98.0,0.500,11.1,0.8,-4.5,-0.4,15.9,1.1,0.198,-4.0,3.5,-0.9,9.3,1.7,13.8,9.5,51.1,19.7,-0.6,0.2,0.010,0.0
19374,19374,Zion Williamson,2024,PF,23.0,NOP,70.0,31.5,8.9,15.6,57.0,0.1,0.3,33.3,8.8,15.4,57.4,57.3,5.0,7.1,70.2,1.7,4.1,5.8,5.0,1.1,0.7,2.8,2.3,22.9,618.0,1076.0,6.0,18.0,352.0,47.0,284.0,624.0,1094.0,347.0,494.0,2207.0,122.0,159.0,1601.0,77.0,193.0,406.0,113.0,119.0,0.016,26.5,2.1,3.8,0.6,14.2,2.8,0.452,3.3,6.2,4.7,22.8,1.7,12.8,10.2,61.0,29.7,3.3,7.5,0.164,0.0

In [6]:
engine1 = sqlalchemy.create_engine("sqlite:///../../DB/ballbase.db")  
engine2 = sqlalchemy.create_engine('postgresql+psycopg2://brandon:access@localhost:5432/ballbase' ) 
pd.read_sql('master_2024_25', con=engine1).head(20)

,PLAYER,AGE,TEAM,POS,GP,GS,MPG,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,EFG%,FT,FTA,FT%,ORPG,DRPG,RPG,APG,SPG,BPG,TOPG,PF,PPG,T2P,T2PA,T3P,T3PA,TAST,TBLK,TDRB,TFG,TFGA,TFT,TFTA,TMP,TORB,TPF,TPTS,TSTL,TTOV,TTRB,DRTG,ORTG,3PAR,AST%,BLK%,BPM,DBPM,DRB%,DWS,FTR,OBPM,ORB%,OWS,PER,STL%,TOV%,TRB%,TS%,USG%,VORP,WS,WS/48
0,Shai Gilgeous-Alexander,26.0,OKC,PG,76.0,76.0,34.2,11.3,21.8,51.9,2.1,5.7,37.5,9.2,16.1,57.1,56.9,7.9,8.8,89.8,0.9,4.1,5.0,6.4,1.7,1.0,2.4,2.2,32.7,697.0,1221.0,163.0,435.0,486.0,77.0,312.0,860.0,1656.0,601.0,669.0,2598.0,67.0,164.0,2484.0,131.0,183.0,379.0,107.0,129.0,0.263,31.3,3.0,11.5,2.6,12.6,4.8,0.404,8.9,2.8,11.9,30.7,2.4,8.6,7.8,63.7,34.8,8.9,16.7,0.309
1,Giannis Antetokounmpo,30.0,MIL,PF,67.0,67.0,34.2,11.8,19.7,60.1,0.2,0.9,22.2,11.6,18.7,62.0,60.7,6.5,10.6,61.7,2.2,9.7,11.9,6.5,0.9,1.2,3.1,2.3,30.4,779.0,1256.0,14.0,63.0,433.0,78.0,651.0,793.0,1319.0,436.0,707.0,2289.0,147.0,155.0,2036.0,58.0,206.0,798.0,109.0,122.0,0.048,36.0,3.2,9.5,2.5,29.7,3.7,0.536,6.9,7.3,7.8,30.5,1.2,11.2,19.0,62.5,35.2,6.6,11.5,0.241
2,Nikola Jokić,29.0,DEN,C,70.0,70.0,36.7,11.2,19.5,57.6,2.0,4.7,41.7,9.3,14.8,62.7,62.7,5.2,6.4,80.0,2.9,9.9,12.7,10.2,1.8,0.6,3.3,2.3,29.6,648.0,1033.0,138.0,331.0,716.0,45.0,692.0,786.0,1364.0,361.0,451.0,2571.0,200.0,160.0,2071.0,127.0,230.0,892.0,111.0,133.0,0.243,44.1,1.6,13.3,3.3,28.2,3.8,0.331,9.9,9.0,12.7,32.0,2.4,12.8,19.1,66.3,29.5,9.8,16.4,0.307
3,Luka Dončić,25.0,DAL-LAL,PG,50.0,50.0,35.4,9.2,20.5,45.0,3.5,9.6,36.8,5.7,10.9,52.2,53.6,6.2,7.9,78.2,0.8,7.4,8.2,7.7,1.8,0.4,3.6,2.5,28.2,284.0,544.0,177.0,481.0,383.0,21.0,369.0,461.0,1025.0,309.0,395.0,1769.0,40.0,126.0,1408.0,89.0,179.0,409.0,112.0,116.0,0.469,36.1,1.1,6.7,1.2,22.6,2.4,0.385,5.5,2.6,3.5,24.1,2.5,13.0,12.8,58.7,33.9,3.9,5.9,0.160
4,Anthony Edwards,23.0,MIN,SG,79.0,79.0,36.3,9.1,20.4,44.7,4.1,10.3,39.5,5.1,10.1,50.1,54.7,5.3,6.3,83.7,0.8,4.9,5.7,4.5,1.2,0.6,3.2,1.9,27.6,401.0,801.0,320.0,811.0,359.0,51.0,389.0,721.0,1612.0,415.0,496.0,2871.0,61.0,150.0,2177.0,91.0,249.0,450.0,112.0,115.0,0.503,20.9,1.7,4.3,0.0,14.8,3.8,0.308,4.4,2.4,4.6,20.1,1.6,12.0,8.7,59.5,31.4,4.6,8.4,0.140
5,Jayson Tatum,26.0,BOS,PF,72.0,72.0,36.4,9.2,20.3,45.2,3.5,10.1,34.3,5.7,10.2,55.9,53.7,5.0,6.1,81.4,0.7,8.0,8.7,6.0,1.1,0.5,2.9,2.2,26.8,412.0,737.0,250.0,728.0,431.0,38.0,575.0,662.0,1465.0,358.0,440.0,2624.0,48.0,157.0,1932.0,76.0,209.0,623.0,110.0,117.0,0.497,27.0,1.3,5.2,0.8,23.7,4.2,0.300,4.4,2.0,5.3,21.7,1.5,11.2,12.9,58.2,31.2,4.8,9.5,0.174
6,Kevin Durant,36.0,PHO,PF,62.0,62.0,36.5,9.5,18.1,52.7,2.6,6.0,43.0,7.0,12.1,57.4,59.8,4.9,5.8,83.9,0.4,5.7,6.0,4.2,0.8,1.2,3.1,1.7,26.6,432.0,752.0,160.0,372.0,263.0,77.0,351.0,592.0,1124.0,303.0,361.0,2265.0,23.0,104.0,1647.0,50.0,190.0,374.0,119.0,117.0,0.331,19.6,3.2,3.2,-0.7,16.9,1.2,0.321,3.9,1.2,4.0,21.2,1.1,12.9,9.2,64.2,28.7,3.0,5.2,0.111
7,Tyrese Maxey,24.0,PHI,PG,52.0,52.0,37.7,9.2,21.0,43.7,3.1,9.2,33.7,6.1,11.8,51.5,51.1,4.9,5.6,87.9,0.3,3.1,3.3,6.1,1.8,0.4,2.4,2.2,26.3,316.0,613.0,161.0,478.0,317.0,21.0,159.0,477.0,1091.0,254.0,289.0,1960.0,15.0,116.0,1369.0,91.0,124.0,174.0,119.0,114.0,0.438,28.0,1.1,2.0,-1.1,9.6,1.0,0.265,3.2,0.8,2.9,19.5,2.3,9.2,5.0,56.2,29.8,2.0,3.8,0.094
8,Cade Cunningham,23.0,DET,PG,70.0,70.0,35.0,9.8,20.8,46.9,2.1,6.0,35.6,7.6,14.8,51.5,52.1,4.5,5.3,84.6,0.8,5.3,6.1,9.1,1.0,0.8,4.4,2.8,26.1,535.0,1039.0,149.0,418.0,638.0,53.0,369.0,684.0,1457.0,313.0,370.0,2452.0,56.0,195.0,1830.0,71.0,309.0,425.0,113.0,112.0,0.287,43.0,2.1,3.9,0.1,16.5,2.9,0.254,3.8,2.5,3.0,20.6,1.4,16.0,9.6,56.5,33.2,3.7,5.9,0.115
9,Jalen Brunson,28.0,NYK,PG,65.0,65.0,35.4,9.0,18.5,48.8,2.3,6.1,38.3,6.7,12.4,53.9,55.1,5.7,6.9,82.1,0.4,2.5,2.9,7.3,0.9,0.1,2.5,2.1,26.0,433.0,803.0,152.0,397.0,475.0,8.0,160.0,585.0,1200.0,368.0,448.0,2301.0,27.0,138.0,1690.0,60.0,164.0,187.0,118.0,123.0,0.331,32.3,0.3,3.3,-1.3,7.9,1.4,0.373,4.7,1.4,6.8,21.6,1.3,10.5,4.7,60.5,29.5,3.1,8.3,0.172
10,Paolo Banchero,22.0,ORL,PF,46.0,46.0,34.4,9.0,19.8,45.2,1.9,5.9,32.0,7.1,13.9,50.9,50.0,6.1,8.4,72.7,1.1,6.4,7.5,4.8,0.8,0.6,3.0,2.1,25.9,325.0,639.0,87.0,272.0,219.0,28.0,294.0,412.0,911.0,280.0,385.0,1582.0,51.0,97.0,1191.0,36.0,136.0,345.0,110.0,109.0,0.299,26.0,1.7,3.5,0.2,22.4,2.4,0.423,3.4,3.5,1.1,20.0,1.1,11.2,12.5,55.1,33.6,2.2,3.5,0.106
11,Devin Booker,28.0,PHO,SG,75.0,75.0,37.3,8.7,18.9,46.1,2.4,7.3,33.2,6.3,11.6,54.2,52.5,5.8,6.4,89.4,1.0,3.1,4.1,7.1,0.9,0.2,2.9,2.6,25.6,471.0,869.0,183.0,551.0,529.0,16.0,229.0,654.0,1420.0,432.0,483.0,2795.0,76.0,198.0,1923.0,67.0,220.0,305.0,123.0,119.0,0.388,30.6,0.5,0.4,-2.4,8.9,0.3,0.340,2.8,3.1,6.1,19.3,1.2,11.9,6.1,58.9,29.3,1.7,6.4,0.111
12,LaMelo Ball,23.0,CHO,PG,47.0,47.0,32.0,8.6,21.3,40.5,3.8,11.2,33.9,4.8,10.1,47.8,49.4,4.1,4.9,84.3,1.0,3.9,4.9,7.4,1.1,0.3,3.6,3.3,25.2,227.0,475.0,179.0,528.0,346.0,13.0,185.0,406.0,1003.0,193.0,229.0,1505.0,47.0,157.0,1184.0,54.0,167.0,232.0,117.0,108.0,0.526,43.8,0.8,3.2,-0.9,13.4,1.1,0.228,4.1,3.3,0.9,19.1,1.8,13.1,8.2,53.6,35.9,2.0,2.0,0.065
13,Damian Lillard,34.0,MIL,PG,58.0,58.0,36.1,7.7,17.1,44.8,3.4,9.0,37.6,4.3,8.1,52.8,54.7,6.2,6.8,92.1,0.5,4.2,4.7,7.1,1.2,0.2,2.8,1.7,24.9,247.0,468.0,197.0,524.0,410.0,10.0,243.0,444.0,992.0,362.0,393.0,2093.0,29.0,97.0,1447.0,70.0,162.0,272.0,115.0,122.0,0.528,29.7,0.4,4.0,-0.6,12.1,2.0,0.396,4.7,1.6,5.6,21.3,1.6,12.2,7.1,62.1,27.8,3.2,7.6,0.175
14,Kyrie Irving,32.0,DAL,SG,50.0,50.0,36.1,8.9,18.9,47.3,2.9,7.2,40.1,6.1,11.7,51.7,54.9,3.9,4.3,91.6,1.2,3.6,4.8,4.6,1.3,0.5,2.2,2.0,24.7,303.0,586.0,144.0,359.0,231.0,23.0,180.0,447.0,945.0,196.0,214.0,1804.0,60.0,101.0,1234.0,66.0,111.0,240.0,118.0,118.0,0.380,20.5,1.1,3.4,-0.5,10.6,1.3,0.226,3.9,3.7,3.4,19.9,1.8,9.7,7.2,59.4,27.4,2.5,4.6,0.124
15,Anthony Davis,31.0,LAL-DAL,PF,51.0,51.0,33.5,9.2,17.8,51.6,0.7,2.4,28.2,8.5,15.4,55.3,53.6,5.6,7.2,77.5,2.6,8.9,11.6,3.5,1.2,2.2,2.2,1.9,24.7,435.0,786.0,35.0,124.0,181.0,110.0,456.0,470.0,910.0,286.0,369.0,1706.0,134.0,98.0,1261.0,59.0,113.0,590.0,108.0,118.0,0.136,18.3,6.0,5.4,1.5,29.1,3.0,0.405,3.9,9.1,3.7,26.3,1.7,9.5,19.4,58.8,30.4,3.2,6.7,0.188
16,Zion Williamson,24.0,NOP,PF,30.0,30.0,28.6,9.6,16.9,56.7,0.1,0.4,23.1,9.5,16.5,57.6,57.0,5.3,8.0,65.6,2.5,4.7,7.2,5.3,1.2,0.9,3.0,2.7,24.6,285.0,495.0,3.0,13.0,159.0,27.0,140.0,288.0,508.0,158.0,241.0,857.0,76.0,82.0,737.0,37.0,90.0,216.0,118.0,117.0,0.026,36.6,3.0,7.0,1.0,18.2,0.6,0.474,5.9,9.3,1.9,27.3,2.1,12.8,13.6,60.0,34.7,1.9,2.5,0.141
17,Stephen Curry,36.0,GSW,PG,70.0,70.0,32.2,8.1,18.0,44.8,4.4,11.2,39.7,3.6,6.8,53.4,57.2,4.0,4.3,93.3,0.6,3.9,4.4,6.0,1.1,0.4,2.9,1.4,24.5,253.0,474.0,311.0,784.0,421.0,30.0,270.0,564.0,1258.0,279.0,299.0,2252.0,40.0,95.0,1718.0,80.0,200.0,310.0,113.0,120.0,0.623,31.3,1.3,6.3,0.0,13.3,2.7,0.238,6.4,1.9,5.2,21.5,1.7,12.6,7.4,61.8,29.8,4.8,7.9,0.168
18,Karl-Anthony Towns,29.0,NYK,C,72.0,72.0,35.0,8.9,16.9,52.6,2.0,4.7,42.0,6.9,12.2,56.7,58.4,4.7,5.7,82.9,2.9,9.8,12.8,3.1,1.0,0.7,2.7,3.5,24.4,497.0,877.0,142.0,338.0,222.0,50.0,708.0,639.0,1215.0,339.0,409.0,2517.0,212.0,249.0,1759.0,71.0,192.0,920.0,110.0,122.0,0.278,13.8,1.9,3.6,0.1,32.0,3.8,0.337,3.5,9.8,6.3,23.4,1.4,12.1,21.0,63.0,27.4,3.5,10.1,0.193
19,LeBron James,40.0,LAL,SF,70.0,70.0,34.9,9.3,18.1,51.3,2.1,5.7,37.6,7.2,12.5,57.4,57.1,3.7,4.7,78.2,1.0,6.8,7.8,8.2,1.0,0.6,3.7,1.4,24.4,502.0,874.0,149.0,396.0,575.0,39.0,474.0,651.0,1270.0,259.0,331.0,2444.0,72.0,99.0,1710.0,70.0,260.0,546.0,114.0,117.0,0.312,40.3,1.5,5.6,0.7,21.2,2.8,0.261,4.9,3.4,4.9,22.7,1.4,15.5,12.6,60.4,30.1,4.7,7.7,0.152

# Output to HTML Templates

In [7]:
import sys, os 
sys.path.append(os.path.abspath(os.path.join(os.path.dirname('functions.py'), '..', '..', 'PY')))   
import functions 

engine1 = sqlalchemy.create_engine("sqlite:///../../DB/ballbase.db") 
seasons = functions.generate_seasons(1949, 2025)  
for season in seasons:
    season_str = season 
    master = pd.read_sql("master_"+season, con=engine1).fillna(0) 
    if '3P' in master.columns: 
        averages = master[['PLAYER', 'POS', 'TEAM', 'AGE', 'PPG', 'RPG', 'APG', 'SPG', 'BPG', 'TOPG', 'MPG', 'FG', 'FGA', 'FG%', '3P', '3PA', '3P%', '2P%', 'FT', 'FTA', 'FT%', 'PF']] 
        totals = master.loc[:, ['PLAYER', 'TPTS', 'TSTL',
            'TTOV', 'TTRB', 'T2P', 'T2PA', 'T3P', 'T3PA', 'TAST', 'TBLK', 'TDRB',
            'TFG', 'TFGA', 'TFT', 'TFTA', 'TMP', 'TORB', 'TPF']]
        advanced = master.loc[:, ['PLAYER', 'DRTG', 'ORTG',
            '3PAR', 'AST%', 'BLK%', 'BPM', 'DBPM', 'DRB%', 'DWS', 'FTR', 'OBPM',
            'ORB%', 'OWS', 'PER', 'STL%', 'TOV%', 'TRB%', 'TS%', 'EFG%', 'USG%', 'VORP',
            'WS', 'WS/48']] 
    elif 'BPG' in master.columns:  
        averages = master[['PLAYER', 'POS', 'TEAM', 'AGE', 'PPG', 'RPG', 'APG', 'SPG', 'BPG', 'MPG', 'FGA', 'FG%', '2P%', 'FTA', 'FT%', 'PF']] 
        totals = master.loc[:, ['PLAYER', 'POS', 'TEAM', 'AGE', 'TPTS', 'TSTL', 'TTRB', 'T2P', 'T2PA', 'TAST', 'TBLK', 'TDRB', 'TFG', 'TFGA', 'TFT', 'TFTA', 'TMP', 'TORB', 'TPF']]
        advanced = master.loc[:, ['PLAYER', 'POS', 'TEAM', 'AGE', 'DRTG', 'AST%', 'BLK%', 'BPM', 'DBPM', 'DRB%', 'DWS', 'FTR', 'OBPM',
            'ORB%', 'OWS', 'PER', 'STL%', 'TRB%', 'TS%', 'EFG%', 'VORP',
            'WS', 'WS/48']] 
    elif 'RPG' in master.columns: 
        averages = master[['PLAYER', 'POS', 'TEAM', 'AGE', 'PPG', 'RPG', 'APG', 'GP', 'FGA', 'FG%', '2P%', 'FTA', 'FT%', 'PF']]  
        totals = master.loc[:, ['PLAYER', 'POS', 'TEAM', 'AGE', 'TPTS', 'TAST', 'TTRB', 'T2P', 'T2PA', 'TFG', 'TFGA', 'TFT', 'TFTA', 'TPF']] 
        advanced = master.loc[:, ['PLAYER', 'POS', 'TEAM', 'AGE', 'DWS', 'FTR', 'OWS', 'TS%', 'EFG%', 'WS']]   
    else: 
        averages = master[['PLAYER', 'POS', 'TEAM', 'AGE', 'PPG', 'APG', 'FGA', 'FG%', '2P%', 'FTA', 'FT%', 'PF']] 
        totals = master.loc[:, ['PLAYER', 'POS', 'TEAM', 'AGE', 'T2P', 'T2PA', 'TAST', 'TFG', 'TFGA', 'TFT', 'TFTA', 'TPF', 'TPTS']] 
        advanced = master.loc[:, ['PLAYER', 'POS', 'TEAM', 'AGE', 'DWS', 'FTR', 'OWS', 'TS%', 'WS']] 


    contents = [averages, totals, advanced] 
    # Create HTML table version 
    for i in range(len(contents)):
        contents[i] = contents[i].to_html(table_id="table", classes = "table table-hover table-stripped table-bordered table-striped", border=1, index=False)
        contents[i] = contents[i].replace('<table border="1" class="dataframe table table-hover table-stripped table-bordered table-striped" id="table">', '<table border="1" class="dataframe table table-hover table-stripped table-bordered" style="width:100%" id="table">')
    # Create page content 
    for i in range(len(contents)):
        contents[i] = f"""
{{%extends 'Main/TableBase.html'%}}
{{% block table %}} 

{contents[i]}
{{% endblock %}}
"""
    def write_to_file(path, content): 
        file = open(path, "w", encoding="utf-8") 
        file.write(content) 
        file.close 


    file_names=[f"Averages_{season}.html", f"Totals_{season}.html", f"Advanced_{season}.html"] 

    for i in range(len(contents)): 
        path = f"../../templates/Tables/{file_names[i]}" 
        write_to_file(path, contents[i])